# Generated by Django 5.0.4 on 2026-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerauth',
            name='provider',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('deezer', 'Deezer'), ('apple_music', 'Apple Music'), ('tidal', 'Tidal'), ('soundcloud', 'SoundCloud'), ('amazon_music', 'Amazon Music'), ('youtube_music', 'YouTube Music')], max_length=20),
        ),
    ]
