# Generated by Django 4.2.6 on 2026-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_providerauth_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerauth",
            name="provider",
            field=models.CharField(
                choices=[
                    ("spotify", "Spotify"),
                    ("deezer", "Deezer"),
                    ("apple_music", "Apple Music"),
                    ("tidal", "Tidal"),
                    ("soundcloud", "SoundCloud"),
                    ("amazon_music", "Amazon Music"),
                    ("youtube_music", "YouTube Music"),
                    ("boomplay", "Boomplay"),
                ],
                max_length=20,
            ),
        ),
    ]
