# Generated by Django 5.0.4 on 2026-04-17 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isrc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(blank=True, max_length=500, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('media_type', models.CharField(choices=[('AUDIO', 'Audio (MP3)'), ('VIDEO', 'Vidéo (MP4)')], default='AUDIO', max_length=10)),
                ('prefer_video', models.BooleanField(default=False)),
                ('quality', models.CharField(blank=True, max_length=20, null=True)),
                ('explicit_filter', models.BooleanField(default=False)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='downloads/')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='downloader.trackmetadata')),
            ],
        ),
    ]
