# Generated by Django 5.0.4 on 2026-04-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='media_type',
            field=models.CharField(choices=[('AUDIO', 'Audio (MP3)'), ('VIDEO', 'Vidéo (MP4)'), ('WAV', 'Professionnel (WAV)'), ('FLAC', 'Professionnel (FLAC)'), ('ALAC', 'Professionnel (ALAC/Apple)'), ('OPUS', 'WebRadio (OPUS)'), ('AAC', 'WebRadio/TV (AAC)'), ('MKV', 'Haute Qualité Vidéo (MKV)')], default='AUDIO', max_length=10),
        ),
    ]
