# Generated by Django 5.0.4 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0002_alter_downloadtask_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtask",
            name="error_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

